### 查询服务
GET http://127.0.0.1:9001/imooc/ecommerce-nacos-client/nacos-client/service-instance
Accept:application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOiJ7XCJpZFwiOjE4LFwibmFtZVwiOlwiemdiXCJ9IiwianRpIjoiNjgxMmYwNTItZmVmZC00MGI2LTk0NTItMWFjYzQzZTM4YTAzIiwiZXhwIjoxNjQ5MjYwODAwfQ.gBcV41vajyulidh5ovOuk30ppU1s0y_jSTUkwW3rwif5Qlyj_SMJCXB_zjjaEwpaEvo-WfQJOb24lL-nW1Fom8jfHutDbpw3bUsd7H0AFwkH4-EPAoeBNYknPV3Xef82rYz0hJIZWORBLM0e0UpFeevGlH5iC39h_nvBtj0UIJyJwfxqa6DN-w2sdC8uUGW2UnQwsMea5SgLEcckisNYz-p-FPjTh3XKkttlPat7efxg69UrOG2X7Gfi5sL_lDWKCbMLC5sc5yHWe20Qk4UY_dqFQRga6Se5cf_K1v4jCq29pOvqk-jmuIY-jOw7qTamQoURUlCWoiKgnwL9V9EO0A
token: imooc