### 查询服务
GET http://127.0.0.1:9001/imooc/ecommerce-nacos-client/nacos-client/service-instance
Accept:application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOiJ7XCJpZFwiOjE4LFwibmFtZVwiOlwiemdiXCJ9IiwianRpIjoiNTQxMzA4NDItZWVlYS00MmEzLWI4MzUtMTdmNjkwYWZkYTZhIiwiZXhwIjoxNjM5MzI0ODAwfQ.Z_ow1AEPGTp-LjhIXclj_stIMTLxmE_7YjHrnC47M6CFqaQ73d22cfDYE1QJemyRIiG3MR0tTF-TAjnkUtXJdoLPt4-l8gFGyk50pN2zhIQCWzw86JR8d8GTP2D2zIFcehx4ZjU-3lvd1VZpLZe5OhLH7JMMpRWDZI0lvHkF_EZUlitA2lx_g0uJrrKkQpITVHGB4T5iM4Gol2ptKEQ19e9lXIJwmKWV4J4ZhnBFRAA5PeCXOxBZiQXZOtOyIoVXCIpScILnwc7BbKifZ0u9-rte3k6M8C_iKcabzsZdu8uYY3v0cbLvsUtc5msJHjsYXudqxqgrqGCrVTA_F1wqQQ
token: imooc